# Database credentials
database:
  credentials:
    user:
    password:
    host: localhost
    name:
  schema: dof
# Config for usa_state_oas.py
usa_state_oas:
  # DOF file path, note - file that contains all USA states, countries
  file_path: DOF.DAT
  # Number of rows to skip (header lines)
  skip_rows: 4
  # Note columns numeration consumed as in Python string slicing: from - inclusive, to - exclusive
  # Columns from DOF file for OAS code.
  oas_code:
    col_from: 0
    col_to: 2
  # Columns from DOF file for country code
  ctry_code:
    col_from: 15
    col_to: 17
  # Input file encoding
  encoding: "latin-1"
# Config for load_countries_states.py
load_countries_states:
  countries:
    # Path to the file with country data
    input_file:
    # Input file column name to use for mapping source file country code - DOF country code rules
    column: ADM0_A3
    # Source file country code - DOF oas code rules
    input_dof_map:
      CAN: CA # Canada
      MEX: MX # Mexico
      PRI: PR # Puerto Rico
      BHS: BS # Bahamas
      ATG: AG # Antigua and Barbuda
      AIA: AI # Anguilla
      # Netherlands Antilles (formerly AN)
      ABW: AW # Aruba
      CUB: CU # Cuba
      DMA: DM # Dominica
      DOM: DO # Dominican Republic
      # GP - Guadeloupe
      HND: HN # Honduras
      HTI: HT # Haiti
      JAM: JM # Jamaica
      # KN - St. Kitts and Nevis
      CYM: KY # Cayman Islands
      LCA: LC # Saint Lucia
      # MQ - Martinique
      MSR: MS # Montserrat
      TCA: TC # Turks and Caicos Islands
      VGB: VG # British Virgin Islands
      VIR: VI # Virgin Islands
      ASM: AS # American Samoa
      FSM: FM # Federated States of Micronesia
      GUM: GU # Guam
      KIR: KI # Kiribati
      MHL: MH # Marshall Islands
      # QM - Midway Islands (formerly MI)
      MNP: MP # Northern Mariana Islands
      PLW: PW # Palau
      RUS: RU # Russia
      # TK - Tokelau
      # QW - Wake Island (formerly WQ)
      WSM: WS # Samoa
      USA: US # USA, note: USA as country is not used in DOF (obstacles are assigned to the USA states)
  usa_states:
    # Path to the file with country data
    input_file:
    # Input file column name to use for mapping source file country code - DOF country code rules
    ctry_column: adm0_a3
    state_column: postal
    # Source file country code - DOF oas code rules
    input_dof_map:
      AL: "01"
      AK: "02"
      AZ: "04"
      AR: "05"
      CA: "06"
      CO: "08"
      CT: "09"
      DE: "10"
      DC: "11"
      FL: "12"
      GA: "13"
      HI: "15"
      ID: "16"
      IL: "17"
      IN: "18"
      IA: "19"
      KS: "20"
      KY: "21"
      LA: "22"
      ME: "23"
      MD: "24"
      MA: "25"
      MI: "26"
      MN: "27"
      MS: "28"
      MO: "29"
      MT: "30"
      NE: "31"
      NV: "32"
      NH: "33"
      NJ: "34"
      NM: "35"
      NY: "36"
      NC: "37"
      ND: "38"
      OH: "39"
      OK: "40"
      OR: "41"
      PA: "42"
      RI: "44"
      SC: "45"
      SD: "46"
      TN: "47"
      TX: "48"
      UT: "49"
      VT: "50"
      VA: "51"
      WA: "53"
      WV: "54"
      WI: "55"
      WY: "56"
