# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DigitalObstacleFileManager
                                 A QGIS plugin
 Manage FAA DOF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-17
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QWidget, QMessageBox
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .dof_manager_dialog import DigitalObstacleFileManagerDialog
import os.path


class DigitalObstacleFileManager:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DigitalObstacleFileManager_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FAA_DOF')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.layers = {}
        """Layers required in project"""

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DigitalObstacleFileManager', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/dof_manager/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'DOF Manager'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FAA_DOF'),
                action)
            self.iface.removeToolBarIcon(action)

    def _is_layer_loaded(self, layer_name: str) -> bool:
        """Check if layer is loaded to QGIS project.
        :param layer_name: layer name to be checked
        :type layer_name: str
        :return: True if only one layer with given name is loaded
        :rtype: bool
        """
        layers = QgsProject.instance().mapLayersByName(layer_name)
        layers_count = len(layers)
        if not layers:
            QMessageBox.critical(QWidget(), "Message", f"'{layer_name}' layer not found!\n"
                                                       f" Add layer.")
            return False
        elif layers_count > 1:
            QMessageBox.critical(QWidget(), "Message", f"{layers_count} layers  '{layer_name}' found in Layers.\n"
                                                       f"Only one layer '{layer_name}' is allowed!\n"
                                                       f"Remove unnecessary layers.")
            return False

        self.layers[layer_name] = layers[0]

        return True

    def _is_postgis_storage(self, layer_name: str) -> bool:
        """Check if layer is 'PostgreSQL database with PostGIS extension' storage type.
        :param layer_name: layer name to be checked
        :type layer_name: str
        :return: True if 'PostgreSQL database with PostGIS extension' is storage type for given layer
        :rtype: bool
        """
        expected_storage = "PostgreSQL database with PostGIS extension"
        provider = self.layers[layer_name].dataProvider()
        actual_storage = provider.storageType()

        if actual_storage != expected_storage:
            QMessageBox.critical(QWidget(), "Message", f"Current provider type: {actual_storage} for "
                                                       f"layer '{layer_name}'.\n"
                                                       f"Expected provider type: {expected_storage}.\n")
            return False

        return True

    def _is_layer_correct(self, layer_name):
        """Check if correct layers is loaded (layer name, storage type)
        :param layer_name: layer name to be checked
        :type layer_name: str
        :return: True if given layer name is loaded and has 'PostgreSQL database with PostGIS extension' storage type
        :rtype: bool
        """
        return self._is_layer_loaded(layer_name) and self._is_postgis_storage(layer_name)

    def _check_loaded_layers(self) -> bool:
        """Check required layers in current QGIS project.
        :return: True if required layers and their storage type are correct
        :rtype: bool
        """
        layers = ["country", "obstacle", "us_state"]
        return all([self._is_layer_correct(layer) for layer in layers])

    def run(self):
        """Run method that performs all the real work"""
        if not self._check_loaded_layers():
            return

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = DigitalObstacleFileManagerDialog()

            self.dlg.pushButtonCancel.clicked.connect(self.dlg.close)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        self.dlg.exec_()
